### ISSUE TITLE
加载失败

### ISSUE THREAD

**Issue by Valistars** [XiaoHuiHui233/AutoQuickBackup#4]
[MCDR] [11:48:56] [TaskExecutor/ERROR]: 插件 RegularPlugin[file=AutoQuickBackup.py,path=plugins\AutoQuickBackup.py,state=0] 加载失败
Traceback (most recent call last):
  File "D:\servers\server服务端\MCDR_Server\mcdreforged\plugin\plugin_manager.py", line 167, in __load_plugin
    plugin.load()
  File "D:\servers\server服务端\MCDR_Server\mcdreforged\plugin\regular_plugin.py", line 87, in load
    self.__load_instance()
  File "D:\servers\server服务端\MCDR_Server\mcdreforged\plugin\regular_plugin.py", line 67, in __load_instance
    self.module_instance = misc_util.load_source(self.file_path)
  File "D:\servers\server服务端\MCDR_Server\mcdreforged\utils\misc_util.py", line 31, in load_source
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "plugins\AutoQuickBackup.py", line 7, in <module>
    from utils.rtext import *
ModuleNotFoundError: No module named 'utils'

**Comment by Valistars** [comment]
ok
