### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by POEG1726** [XiaoHuiHui233/AutoQuickBackup#5]
MCDR1.5.0
无法加载插件
~~~
[MCDR] [00:48:51] [TaskExecutor/ERROR]: 插件 RegularPlugin[file=AutoQuickBackup.py,path=plugins\AutoQuickBackup.py,state=0] 加载失败
Traceback (most recent call last):
  File "C:\server\MCDR\mcdreforged\plugin\plugin_manager.py", line 167, in __load_plugin
    plugin.load()
  File "C:\server\MCDR\mcdreforged\plugin\regular_plugin.py", line 87, in load
    self.__load_instance()
  File "C:\server\MCDR\mcdreforged\plugin\regular_plugin.py", line 67, in __load_instance
    self.module_instance = misc_util.load_source(self.file_path)
  File "C:\server\MCDR\mcdreforged\utils\misc_util.py", line 31, in load_source
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\server\MCDR\plugins\AutoQuickBackup.py", line 7, in <module>
    from utils.rtext import *
ModuleNotFoundError: No module named 'utils'
~~~

**Comment by Cindy-miller** [comment]
> MCDR1.5.0
> 无法加载插件
> 
> ```
> [MCDR] [00:48:51] [TaskExecutor/ERROR]: 插件 RegularPlugin[file=AutoQuickBackup.py,path=plugins\AutoQuickBackup.py,state=0] 加载失败
> Traceback (most recent call last):
>   File "C:\server\MCDR\mcdreforged\plugin\plugin_manager.py", line 167, in __load_plugin
>     plugin.load()
>   File "C:\server\MCDR\mcdreforged\plugin\regular_plugin.py", line 87, in load
>     self.__load_instance()
>   File "C:\server\MCDR\mcdreforged\plugin\regular_plugin.py", line 67, in __load_instance
>     self.module_instance = misc_util.load_source(self.file_path)
>   File "C:\server\MCDR\mcdreforged\utils\misc_util.py", line 31, in load_source
>     spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 855, in exec_module
>   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
>   File "C:\server\MCDR\plugins\AutoQuickBackup.py", line 7, in <module>
>     from utils.rtext import *
> ModuleNotFoundError: No module named 'utils'
> ```
